name: Altenizen
version: '1.0-SNAPSHOT'
main: com.marayd.denizenImplementation.DenizenImplementation
description: "Alternative Depenizen, adds a lot of addons!"
api-version: '1.21'
author: maraydq
depend:
  - Denizen
  - PlasmoVoice
  - ProtocolLib