name: Altenizen
version: '1.0-SNAPSHOT'
main: org.marayd.altenizen.Altenizen
description: "Alternative Depenizen, adds a lot of addons!"
api-version: '1.21.4'
author: maraydq
depend:
  - Denizen
  - PlasmoVoice
  - ProtocolLib