name: Altenizen
version: '1.0-SNAPSHOT'
main: org.mryd.altenizen.Altenizen
description: "Alternative Depenizen, adds a lot of addons!"
api-version: '1.21'
author: mryd
depend:
  - Denizen
  - PlasmoVoice
